# Site settings
title: "Swan Valley Open House"
email: swanvalley@swanvalley.com

collections:
  faculty:
    output: true
    permalink: /:collection/:title

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap